### ISSUE TITLE
Server Authentication JWT Node.js generation

### ISSUE THREAD

**Issue by gander** [centrifugal/centrifugal.dev#28]
When trying to use [`jsonwebtoken`](https://www.npmjs.com/package/jsonwebtoken) in CloudFlare Worker, I encountered this problem: https://github.com/auth0/node-jsonwebtoken/issues/886

```
Could not resolve "buffer"
Could not resolve "util"
Could not resolve "stream"
Could not resolve "crypto"
```

So I suggest that you could either just mention an alternative library that doesn't have this problem:

---
#### found on [jwt.io](https://jwt.io/)

```node
import * as jose from 'jose'

export const onRequest = async (context) => {
    const secret = new TextEncoder().encode(context.env.SECRET_KEY);
    const token = await new jose.SignJWT({sub: ""})
        .setProtectedHeader({ alg: 'HS256' })
        .setIssuedAt()
        .sign(secret)
    return new Response(JSON.stringify({token}));
}
```

---
#### found while looking for a solution for CloudFlare Worker

```node
import jwt from '@tsndr/cloudflare-worker-jwt'

export const onRequest = async (context) => {
    const token = await jwt.sign({sub: ""}, context.env.SECRET_KEY);
    return new Response(JSON.stringify({token}));
}
```

**Comment by FZambia** [comment]
Hello @gander. Thanks for pointing, now using `jose` lib in doc examples for NodeJS
